from .test_exchange import TestExchange
from .test_dmi import TestDMI
from .test_uniaxialanisotropy import TestUniaxialAnisotropy
from .test_cubicanisotropy import TestCubicAnisotropy
from .test_demag import TestDemag
from .test_magnetoelastic import TestMagnetoElastic
from .test_zeeman import TestZeeman
from .test_energy import TestEnergy
from .test_precession import TestPrecession
from .test_damping import TestDamping
from .test_zhangli import TestZhangLi
from .test_slonczewski import TestSlonczewski
from .test_dynamics import TestDynamics
from .test_mindriver import TestMinDriver
from .test_timedriver import TestTimeDriver
from .test_mesh import TestMesh
from .test_compute import TestCompute
from .test_info_file import test_info_file
from .test_save_delete import test_save_delete
from .test_multiple_drives import test_multiple_drives
from .test_stdprob3 import test_stdprob3
from .test_stdprob4 import test_stdprob4
from .test_stdprob5 import test_stdprob5
